site_name: Ross Stockman
site_url: https://ross-stockman.github.io/ross-stockman-blog/

copyright: Copyright &copy; 2025 Ross Stockman
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ross-stockman-5b755176/
    - icon: fontawesome/brands/github
      link: https://github.com/ross-stockman/ross-stockman

theme:
  name: material

  font:
    text: 'Roboto'
    code: 'Roboto Mono'

  logo: assets/logo.png

  features:
    - navigation.footer

  palette:

    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: deep blue
      accent: deep orange

    # Light mode
    - schema: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: deep blue
      accent: deep orange

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

